version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superRootPass
      MYSQL_DATABASE: skiwatch
      MYSQL_USER: skiwatch
      MYSQL_PASSWORD: superUserPass
    volumes:
      - db_data:/var/lib/mysql

  php:
    image: php:8.3-fpm
    restart: always
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    environment:
      DB_HOST: db
      DB_DATABASE: skiwatch
      DB_USERNAME: skiwatch
      DB_PASSWORD: superUserPass
    depends_on:
      - db

  nodebridge:
    image: node:18
    restart: always
    working_dir: /app
    volumes:
      - ./wsbridge:/app
      - ./certbot-data/www:/certs # для доступа к SSL сертификатам
    environment:
      DOMAIN: skiwatch.ru
      PORT: 9443
      SSL_CERT: /certs/live/skiwatch.ru/fullchain.pem
      SSL_KEY: /certs/live/skiwatch.ru/privkey.pem
    command: node bridge.js
    depends_on:
      - php

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel:/var/www:ro
      - ./vue/dist:/var/www/html/spa:ro         # билды Vue копировать сюда
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot-data/www:/etc/letsencrypt
    depends_on:
      - php
      - nodebridge

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot-data/www:/etc/letsencrypt
      - ./certbot-data/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
    environment:
      - TZ=Europe/Moscow

volumes:
  db_data: