server {
    listen 80;
    server_name dev.skiwatch.ru;

    root /frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Статические файлы (картинки, css, js и т.п.)
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2|ttf|eot)$ {
        try_files $uri =404;
        expires max;
        access_log off;
    }

    # Обычно разрешается доступ к файлам-иконкам и manifest
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /manifest.json { access_log off; log_not_found off; }
}